### ISSUE TITLE
Requirements for "finalized" airports

### ISSUE THREAD

**Issue by AdamJCavanaugh** [AdamJCavanaugh/EndlessATCAirports#1]
- We probably need to separate the "raw" files (from the script) from ones that have been edited/finalized by hand. Perhaps simply a second folder named "final" (or similar).
- Do we want to subdivide the "final" folder by region (continent/country, perhaps)?
- I see no reason to exclude truly custom/fantasy airports, which should have their own folder structure under final, perhaps?
- We need to develop requirements for "finalized" airports to determine whether an airport is ready to be copied out of raw or not.
- Should "finalized" airports be removed from "raw" or should that remain for comparison/history?
- Does startgrid want to include certain airports in the game by default (I assume including more airports will also increase the application size, which is not ideal)? Or perhaps allow for live downloading in the game from a specific folder (or branch?) of this repository?

**Comment by aap007freak** [comment]
There should definitely be a separate folder for finalized airports.
Whether or not these custom airports will become a part of the main game is for startgrid to decide I guess.

**Comment by msgallagher** [comment]
i am interested in helping to improve the raw files. let me know what process/folder structure you decide on. for starters i will start working on lszh (zurich). for now i will be cloning directly into D:\Program Files (x86)\Steam\steamapps\common\Endless ATC\locations\ and then copying from raw\lszh_gen.txt to locations\lszh.txt. i will try to submit a pull request, once i have something working ;)

**Comment by AdamJCavanaugh** [comment]
- Unless/until we hear from startgrid, let's plan to leave the ones he provided in "raw" and create a new folder named "final" for those that have received some level of manual attention/testing.
- Since I doubt the UI would handle having dozens (let alone 3137) custom airports added, let's subdivide the "final" directory by continent, then country/state. Unless others have ideas (which is great), I'll plan to use the [ISO 3166-3](https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_%28data_file%29#Data_file) (meaning the 2 letters for continent and 3 letters for country/state). So the finalized LSZH would go under final\EU\CHE. Hopefully this will make it easier for other users/fans to find and move to their own `Steam\steamapps\common\Endless ATC\locations`
- In this vein, fantasy airports will be welcome at final\custom
- Do either of you (or any lurkers) have any practical aviation experience to offer guidelines for testing/verification before moving new airports to "final?" I just enjoy time-management games and listening to ATC recordings, so all the nitty-gritty details are unfamiliar to me, unfortunately...

**Comment by msgallagher** [comment]
Awesome, sounds like a plan. I will submit a PR (pull request) with an early version of final\EU\CHE\LSZH.txt 

I have a commercial pilot license with twin engine IFR rating so I know how to read flight, approach and departure charts and am using those to try and recreate some of the airspace, heading, restrictions etc.. The documentation in the example.txt is quite terse which means that changes require a lot of restarts and testing - slowly getting the hang of it ;)
