### ISSUE TITLE
Contributor request

### ISSUE THREAD

**Issue by dsolesvik** [AdamJCavanaugh/EndlessATCAirports#102]
Hiya, I would love to become a contributor for the project. I have already made an EVRA file (which has one small bug which I'm unable to fix but I'm sure we can fix it together in this repo), as well as a UKBB file and am working on UBBB at this time. In the future, I am also planning to create files for more airports. The data I use is taken from sector files used by Air Traffic Controllers on the VATSIM network and the coordinates of SIDs (and sometimes STARs), waypoints, etc., as well as the Approach sectors are very accurate to what is used IRL, so I believe I can contribute to this project. Many thanks

**Comment by AdamJCavanaugh** [comment]
Anyone is welcome to submit PRs for airports from their fork. See [this guideline](https://www.dataschool.io/how-to-contribute-on-github/) (which is linked in the README.md as well) for information.
