### ISSUE TITLE
LROP/LRBS

### ISSUE THREAD

**Issue by tgpetrica** [AdamJCavanaugh/EndlessATCAirports#104]
I would like to add LROP Bucharest Henri Coanda and LRBS Bucharest Baneasa Airports in EndlessATC.
Both are located in the North side of the capital city of Romania, Bucharest.

**Comment by AdamJCavanaugh** [comment]
Sounds great. If you already have the airport file, please open a Pull Request, following the Contributing guidlines in the Readme (or use [this guide](https://www.dataschool.io/how-to-contribute-on-github/)).

If you need any GitHub or development help, we recommend asking on the [Discord](https://discord.gg/v4wDGh3) (also linked in the Readme). I'll leave this issue open for a while in case you have any further issues or questions.

**Comment by tgpetrica** [comment]
Thank you! I cannot see any channel on the Discord server.

**Comment by AdamJCavanaugh** [comment]
I believe you need to go to the #rules channel (https://discord.com/channels/760583423084593173/760586460796813352), read the rules, and hit the 👍 to gain access to the rest.

**Comment by tgpetrica** [comment]
![image](https://user-images.githubusercontent.com/57829402/117310909-66e6fa80-ae8c-11eb-9dca-6b0db1f38614.png)
Unable to see any channel.

**Comment by AdamJCavanaugh** [comment]
Please confirm you're using this link?

https://discord.gg/v4wDGh3

**Comment by AdamJCavanaugh** [comment]
Closing after 1 month inactivity
