### ISSUE TITLE
CHN/ZG/ZGGG

### ISSUE THREAD

**Issue by LeoChen98** [AdamJCavanaugh/EndlessATCAirports#112]
Airport in progress, it's also work with @savoki0216

**Comment by AdamJCavanaugh** [comment]
You say it's in progress. Should I expect another update soon or review/merge the PR already open?

**Comment by LeoChen98** [comment]
> You say it's in progress. Should I expect another update soon or review/merge the PR already open?

files are not here, wait @savoki0216
