### ISSUE TITLE
Add Directory Structure Requirements to README

### ISSUE THREAD

**Issue by AdamJCavanaugh** [AdamJCavanaugh/EndlessATCAirports#13]
From issue #1:
- Unless/until we hear from startgrid, let's plan to leave the ones he provided in "raw" and create a new folder named "final" for those that have received some level of manual attention/testing.
- Since I doubt the UI would handle having dozens (let alone 3137) custom airports added, let's subdivide the "final" directory by continent, then country/state. Unless others have ideas (which is great), I'll plan to use the ISO 3166-3 (meaning the 2 letters for continent and 3 letters for country/state). So the finalized LSZH would go under final\EU\CHE. Hopefully this will make it easier for other users/fans to find and move to their own Steam\steamapps\common\Endless ATC\locations
- In this vein, fantasy airports will be welcome at final\custom

**Comment by baobao1270** [comment]
Well, please allow me point out two mistakes in your updated README. 

1. Using 2 letters for continent and 3 letters for country/state is not ISO 3166-3, but _ISO 3166-1 alpha-3_.
2. Los Angeles Airport is placed in `final/NA/USA/CA/KLAX.txt` instead of `final/US/CA/KLAX.txt`.

When a country/state have too many airports, I think the third level of sub directory is needed. For example, Los Angeles is placed in `final/NA/USA/CA/KLAX.txt`, and Shanghai Pudong Airport is placed in `final/AS/CN/ZS/ZSPD.txt`

Meanwhile, I recommand that all airport files should use `.txt` extension name.

**Comment by AdamJCavanaugh** [comment]
@baobao1270, thanks so much. I considered leaving this open for a while for review, but just figured no one would. Thank you for proving me wrong. :)

1. Absolutely right. I'll plan to add in a link as well, I think: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3 or https://www.iso.org/obp/ui/#search ?
2. I went off what was there, instead of what should be there... again, great catch. :) I'll need to open another issue/PR to fix the directory there.

**Comment by AdamJCavanaugh** [comment]
Okay, so I think I just referenced ISO 3166 because we use ISO 3166-1 alpha-3 for countries, but this doesn't specify continents. I can't (right now, at least) seem to find an official (ISO) list for the continents.

1. Do you know the documentation for official continent names? I think (based on my history) I used https://datahub.io/core/continent-codes initially. We need something certain here for the 1st directory.
2. We'll use ISO 3166-3 for the 2nd directory.
3. Do you have a specific point ("too many airports") for which we should use a third level? Should we just always use a third level? If so, do you have a specific list in mind for what abbreviation should be used?
4. For .txt extension, I agree, but I guess it's not explicit in the README, so I can add that.

I guess, in summary, I'd like to be able to say we use something like: `final/<continent>/<country>/<state>/<ICAO>.txt and have each <> include the link to the list...

**Comment by AdamJCavanaugh** [comment]
I added some updates and a new branch/PR, if you want to review.
