### ISSUE TITLE
KJ glidepath is out of airspace at WSSS

### ISSUE THREAD

**Issue by ZsBT** [AdamJCavanaugh/EndlessATCAirports#147]
If I change runways, the ILS glidepath to KJ is out of the airspace so flights cannot land, they divert to somewhere.

**Comment by AdamJCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/47431642/128713876-91b0f131-bfde-485a-9295-731403de22bf.png)

**Comment by AdamJCavanaugh** [comment]
I discussed this with the author (Jacob) on Discord, who said he'll expand the airspace to handle this orientation later this week. I'm not confident if Jacob has contributed on GitHub or not (as I believe I've added all his files from the Discord, not here), so I'll not assign it to anyone yet.
