### ISSUE TITLE
LSZH highly inaccurate

### ISSUE THREAD

**Issue by codelyokop** [AdamJCavanaugh/EndlessATCAirports#15]
Coming as a VATSIM controller ive noticed some big problems with LSZH .

This biggest that i saw immediatly is that 0 SID or STARS were provided when they are heavily used, resulting in unrealistic arrivals from all directions when they would be arriving through GIPOL RILAX or AMIKI

The CTR ALT restriction is of incorrect shape (it is dependent on runway config slightly  as well but obviously cant be done here)

There are multiple airports within 30NM with airliner traffic, including LSMD which is inside the ctr of Zurich but is still used by airlines for storage like in recent covid times.

Im highly certain arrival controls much higher than 8000 with arrivals, especially when the holds are in use.

The airlines section includes aircraft not within the swiss fleet anymore

RWY 10 is not used for any landings yet is configured.

When landing 14 which is by default the start then 28 is used for departures and not 16 where you require a 10nm cuttoff point

**Comment by AdamJCavanaugh** [comment]
Hey, thanks for the issue @codelyokop. Have you done any work on the files yourself that I can assign this to you or should we look for another "developer?"

**Comment by codelyokop** [comment]
I am unfamiliar with the format but I did pick those issues up. I am
currently too busy to look into learning the format. I brought it up due to
the fact it was filed under final when theres a level of work that needs to
be done

**Comment by jamesg31** [comment]
The runways can be fairly easily switched. In terms of SIDS and STARS, we could do some very basic work to add departure "gates" with just one waypoint on them to help flow the departures a bit better, but there is no way to do STARS as of now. This is just about at the quality that we are going to need to live with as of now since this airport has almost all features that we can do to make it as realistic as possible.

All the airports in final have major accuracy issues, but final should be a place to store airports that are playable. It really isnt possible to get the level of realism I think your looking for until we get an update to the custom airport system.

**Comment by AdamJCavanaugh** [comment]
Thanks. We're still working on our naming/finalizing scheme; without any testers or real standards, even, we're just putting anything that's been worked on in "final" for now. Probably not the best idea, I suppose. 👍

@msgallagher, as the original contributor on this, do you have any comments or want to work on it?

**Comment by Beaso14** [comment]
I'd like to mention that recreating STARS is possible, albeit extremely
fiddly and time consuming: view the 'transitions' section of the
example.txt

Luke

**Comment by msgallagher** [comment]
> Coming as a VATSIM controller ive noticed some big problems with LSZH .
> 
> This biggest that i saw immediatly is that 0 SID or STARS were provided when they are heavily used, resulting in unrealistic arrivals from all directions when they would be arriving through GIPOL RILAX or AMIKI
> 
> The CTR ALT restriction is of incorrect shape (it is dependent on runway config slightly as well but obviously cant be done here)
> 
> There are multiple airports within 30NM with airliner traffic, including LSMD which is inside the ctr of Zurich but is still used by airlines for storage like in recent covid times.
> 
> Im highly certain arrival controls much higher than 8000 with arrivals, especially when the holds are in use.
> 
> The airlines section includes aircraft not within the swiss fleet anymore
> 
> RWY 10 is not used for any landings yet is configured.
> 
> When landing 14 which is by default the start then 28 is used for departures and not 16 where you require a 10nm cuttoff point

@codelyokop : thanks for your feedback and suggestions on improving LSZH - i basically just tried to get LSZH working without much attention to being super realistic. if i can find some time, i will try to address some of the issues that you brought up. 

however, as @Beaso14 mentioned, STARS and SIDS are quite difficulte to configure and even getting airspace restrictions working without a WYSIWYG editor is quite time consuming.

i am a software developer, so i could probably start on developing an editor however with family, hobbies and everything else happing this is more of a pipe-dream than an attainable goal :P

**Comment by Beaso14** [comment]
Forgot to mention that STARS now work for secondary airports, fixed in a recent hot fix.

**Comment by codelyokop** [comment]
thanks guys, @markus it was nice to see that somebody did a bit of
attention to it, i think the case is when i noticed is with the naming
structure of the github. For SIDS its only really Deges and Vebit in use
with the rare light aircraft on ZUE or WIL departures. as for arrival its
pretty much all through GIPOL, RILAX and AMIKI with nothing to the south.
these 3 would probably be good to put in as fixes like the vor's on EGLL so
that you can hold aircraft there, as these are the main holds.
Kind Regards
Sam

**Comment by msgallagher** [comment]
> I'll work on this issue next week, away at the moment. Runway configs are an easy change and I'll look into the arrival system.

@Beaso14: Did you ever get a chance to work on LSZH? If not, I have some time to address the issues that @codelyokop brought up!

**Comment by Beaso14** [comment]
Sorry for the delays, I'm going to start work on LSZH this afternoon.
