### ISSUE TITLE
Restructure Layout

### ISSUE THREAD

**Issue by AdamJCavanaugh** [AdamJCavanaugh/EndlessATCAirports#151]
A suggestion has been made to change the GitHub folder layout from:
final/continent/country/ICAO.txt
to:
final/countryICAO/ICAO.txt

This would separate countries with many airports in to separate folders, so things like GBR would be much cleaner. It also matches the Discord channel layout better.
However, we'd lose the separation by country, which might be helpful for some users.

I suppose we could even do:
final/continent/country/ICAO/<files>
But I don't know if that's too many folders to go down, especially for countries with only 1 file (like VNM).

Any other thoughts or suggestions?

**Comment by AdamJCavanaugh** [comment]
As an example of the options:

1. final/EU/GBR/EGLL* (current)
2. final/EU/EGLL/EGLL*
3. final/EU/GBR/EGLL/EGLL*

**Comment by AdamJCavanaugh** [comment]
Alternate suggestions from Discord:

- final/continent/letter/ICAO/files (e.g. final/EU/E/EGLL/*)
- final/ICAO/files (e.g. final/EGLL/*)

**Comment by ZsBT** [comment]
I guess those who download and implement custom files to their app are enthusiastics and they has a minimal knowledge about countries and continents.
The 4-letter airport codes are more complex to know from the heart, so in my opinion the structure is not a big issue.

**Comment by AdamJCavanaugh** [comment]
This option "won" on the Discord:
Option 4
final/EU/EGCC/EGCC.txt
final/EU/EGCC/EGCC_readme.md
