### ISSUE TITLE
Endless ATC Custom Airport Discord

### ISSUE THREAD

**Issue by Beaso14** [AdamJCavanaugh/EndlessATCAirports#17]
Hello, would it be beneficial for me to work on a Discord for users of this repository?
It could be used for support and training on how to make Custom Airports so that we get a bit more traffic here?

I contacted Startgrid about making a general Endless ATC one on itch.io but he hasn't got back yet.

**Comment by jamesg31** [comment]
Definitely, I would say so. It would be a great way of communicating as the github issue system is a little clunky for things that are not actual issues.

**Comment by Beaso14** [comment]
_especially_ on mobile

**Comment by Beaso14** [comment]
https://discord.gg/rFkvRS
Discord Link /\ 
There is a text channel for improvements to be made, this server is nowhere near done however

**Comment by AdamJCavanaugh** [comment]
This information should be added to the README...

When I follow the link, I receive a message that the invite was expired. Has anything been changed/updated? @Beaso14

**Comment by Beaso14** [comment]
@AdamJCavanaugh https://discord.gg/v4wDGh3
Still a WIP

**Comment by Beaso14** [comment]
@AdamJCavanaugh Could you possibly put the discord link in the README as a sort of community help link? This issue is basically closed otherwise

**Comment by AdamJCavanaugh** [comment]
Pushed the change directly to master. ;)
