### ISSUE TITLE
[RJTT] ROVER1B departures divert

### ISSUE THREAD

**Issue by thijsschepman** [AdamJCavanaugh/EndlessATCAirports#27]
When playing a north configuaration in RJTT, all ROVER1B departures out of RJTT runway 34R leave the TMA before reaching FL240 and thereby count as being diverted. Either the airspace needs to be expended a little, the minimum level lowered or the departure needs to be a tad longer. Currently most planes reach the border at around FL170.

**Comment by AdamJCavanaugh** [comment]
Just to confirm this is when using the modified RJTT one from this repository, correct?

**Comment by thijsschepman** [comment]
Ow yes, I forgot it was also included in the base game :D

**Comment by AdamJCavanaugh** [comment]
@ckwng is the sole contributor to RJTT at this point, so I'll wait for any updates ckwng  might want to give first.

If ckwng does not update, do you have a preference? The airspace is already quite large (my screen keeps zooming in, if I pause, so I can't see the entire airspace), so I might prefer _not_ to expand it for gameplay reasons... but I feel like it's probably the "right" answer?

**Comment by ckwng** [comment]
Hi,

Unfortunately, RJTT ACA ceiling is FL240 in real life except for a corner in the southwest that is FL230. As per the readme, departures to the west and north must be handed off prior to exiting the ACA. If they are handed off, they can fly outside of the ACA under FL240 without resulting in a diversion.

Actually, I think departures via VAMOS are cutting it pretty close too, as well as some RJAA departures, some might be dependent on aircraft performance and speed.

Given that in real life, planes would be handed off to Tokyo Control anyways at the border, and how much space there is in the ACA (you can hand off planes pretty early ~5000) and the long period of time you have to hand off, I'm inclined not to lower the ceiling. Unfortunately a result of a game limitation where a departure cleared to climb to cruise and proceeding towards the exit point is treated as a diversion (???)...

I think it's a good practice anyways to manually hand off anyways as conflicts near BEKLA and RITLA (departures from both runways converging) are possible as well as east of UTIBO (RJAA departures climbing into RJTT departures).

**Comment by AdamJCavanaugh** [comment]
After further consideration, myself, I believe the manual handoffs is the proper solution, so this issue should be closed. Is that acceptable, @thijsschepman?

**Comment by thijsschepman** [comment]
I think we can close this issue.
