### ISSUE TITLE
Update EGFF with SID's and STAR's.

### ISSUE THREAD

**Issue by Beaso14** [AdamJCavanaugh/EndlessATCAirports#28]
I'll use the online NATS package to get sids and stars into EGFF - I'll also clean up the file in general codewise.

**Comment by Beaso14** [comment]
Is it possible we could drop EGFF from development. It's so small that having so many arrivals feels wrong and I'm likely to work on some larger UK airports next like EGBB or EGPH instead?

**Comment by AdamJCavanaugh** [comment]
I've unassigned you, but I'll leave the issue open in case anyone else wants to start up. Go ahead and work on whatever you want. :D

**Comment by AdamJCavanaugh** [comment]
Closing since there's been no movement for over 90 days.
