### ISSUE TITLE
EU/ES/LEMD

### ISSUE THREAD

**Issue by AdamJCavanaugh** [AdamJCavanaugh/EndlessATCAirports#35]
An alternate [LEMD](https://drive.google.com/file/d/1Xo5x2Ajrsnv39AHkyT_YGppgPr-b1eJy/view) is available. This version contains greater information and should probably be used as a significant update to the existing LEMD.

The new LEMD, however, has issues with approaches triggering altitude violations in restricted zones (reported by chksix on Discord).

**Comment by JBlank19** [comment]
Madrid North: https://drive.google.com/file/d/12BdMzageRKErHHKeN6vtC1Ruma9ZPoRo/view?usp=sharing
Madrid South: https://drive.google.com/file/d/11f9pM1e5ubfu83yXzen1wzKEq96pAR3Y/view?usp=sharing
