### ISSUE TITLE
AS/HKG/VHHH

### ISSUE THREAD

**Issue by ycohui** [AdamJCavanaugh/EndlessATCAirports#52]
Initialized VHHH Airport, with VHHH TMA Area, SID and STAR (Approach).

_Sorry If everything wrong, just new to github_

**Comment by ycohui** [comment]
Hmm... Joint this into #53, and this closed

**Comment by AdamJCavanaugh** [comment]
This issue is fine. The usage of this repository (people submit their own custom airports) isn't necessarily conducive to using issues, but I still like the idea of opening an issue to request/report an airport needing/being customized and linking a PR with the actual changes.

**Comment by ycohui** [comment]
Suggesting about #53 & #54 Naming of File.
maybe we can consider calling by covering area Hong KongFIR (VHHK / VHFR), Hong Kong TMA (VHHH/VHTM), HKIA (VHHH).
or consider by different developed version (as I am develop based on mobile) like calling VHHH (PC) / VHHM (Mobile)
Any thoughts?
