### ISSUE TITLE
only open unitl #1000

### ISSUE THREAD

**Issue by KaiserSeb31** [AdamJCavanaugh/EndlessATCAirports#68]
I can only open the files until number #1000, and it says there are 2017 or so, more  it can not show.
And I´d really like to download KPHL... Has anyone here got the same problem?

**Comment by AdamJCavanaugh** [comment]
Can you please explain the steps to replicate the problem? I'm assuming you're trying to browse the "raw" folder on GitHub in your browser. If so,

1. These are the example auto-generated location files provided by startgrid. They've not been customized, but are (perhaps) a starting point for customization. We don't generally recommend playing them as-is.
2. Best practices would be go clone or fork the whole repo to have all the files available locally.
3. If you really want to view it in your browser, you should be able to click "Go to file" and type what you want.
4. Here's the direct link: https://github.com/AdamJCavanaugh/EndlessATCAirports/blob/master/raw/KPHL_gen.txt

**Comment by KaiserSeb31** [comment]
Thank you. I found Out how it works.👍
________________________________
