### ISSUE TITLE
Transitions for non-main airports

### ISSUE THREAD

**Issue by Beaso14** [AdamJCavanaugh/EndlessATCAirports#7]
Hi, I've been having problem setting up transitions with secondary airports, is it even possible to use transitions with these airports?

The beacon never changes to the triangle and the NAV option never appears.

**Comment by AdamJCavanaugh** [comment]
I've not seen startgrid on GitHub, yet (unless (s)he's going by a different name here). You might try asking on his [blogspot](startgrid.blogspot.com), as I've seen he's replied to some comments there. Or on [itch](https://startgrid.itch.io/custom-airports/community) as there's been some discussion on stuff there; (s)he's had _some_ responses there.

If you find startgrid here or get an answer from elsewhere, please feel free to update the issue and/or add to the README (with a PR)

**Comment by jamesg31** [comment]
I dont believe you can get transitions to work for secondaries. I also couldnt get entrypoints to work properly for secondaries, so it would make sense that transitions also dont work.

Of course I could just be doing something wrong so I would recommend asking on the blogspot. startgrid is pretty active on there.

**Comment by Beaso14** [comment]
> I also couldnt get entrypoints to work properly for secondaries.
Same here, could only give a heading and a beacon, trying to assign a different beacon didnt work.
I'll contact startgrid thanks!
