### ISSUE TITLE
EDDK Airport

### ISSUE THREAD

**Issue by FussballxD** [AdamJCavanaugh/EndlessATCAirports#73]
I've done EDDK for Endless ATC and would like to share it.
[EDDK.txt](https://github.com/AdamJCavanaugh/EndlessATCAirports/files/6144524/EDDK.txt)

**Comment by jamesg31** [comment]
Have you used Github before? Do you know how to open a PR?

**Comment by FussballxD** [comment]
I unfortunately don‘t.

**Comment by jamesg31** [comment]
No worries! Are you in the discord?

**Comment by FussballxD** [comment]
I am

**Comment by jamesg31** [comment]
What is your discord? I will send you a DM

**Comment by FussballxD** [comment]
Philipp Gnech#1021

**Comment by AdamJCavanaugh** [comment]
Thanks, @jamesg31  :)
